services:
  - type: web
    name: apolo-backend
    runtime: python
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./apolo.db
    plan: free
